# Generated by Django 5.0.4 on 2024-05-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacore', '0002_facultad_alter_rol_id_rol_especialidad_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='id_especialidad',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='id_facultad',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_persona',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id_rol',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
