# Generated by Django 5.0.4 on 2024-05-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacore', '0003_alter_especialidad_id_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='id_especialidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='id_facultad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_persona',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id_rol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
